/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// ConnectionRead struct for ConnectionRead
type ConnectionRead struct {
	ConnectionId string `json:"connectionId"`
	Name string `json:"name"`
	NamespaceDefinition *NamespaceDefinitionType `json:"namespaceDefinition,omitempty"`
	// Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.
	NamespaceFormat *string `json:"namespaceFormat,omitempty"`
	// Prefix that will be prepended to the name of each stream when it is written to the destination.
	Prefix *string `json:"prefix,omitempty"`
	SourceId string `json:"sourceId"`
	DestinationId string `json:"destinationId"`
	OperationIds []string `json:"operationIds,omitempty"`
	SyncCatalog AirbyteCatalog `json:"syncCatalog"`
	Schedule ConnectionSchedule `json:"schedule,omitempty"`
	Status ConnectionStatus `json:"status"`
	ResourceRequirements *ResourceRequirements `json:"resourceRequirements,omitempty"`
}

// NewConnectionRead instantiates a new ConnectionRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionRead(connectionId string, name string, sourceId string, destinationId string, syncCatalog AirbyteCatalog, status ConnectionStatus) *ConnectionRead {
	this := ConnectionRead{}
	this.ConnectionId = connectionId
	this.Name = name
	var namespaceDefinition NamespaceDefinitionType = NAMESPACEDEFINITIONTYPE_SOURCE
	this.NamespaceDefinition = &namespaceDefinition
	var namespaceFormat string = "null"
	this.NamespaceFormat = &namespaceFormat
	this.SourceId = sourceId
	this.DestinationId = destinationId
	this.SyncCatalog = syncCatalog
	this.Status = status
	return &this
}

// NewConnectionReadWithDefaults instantiates a new ConnectionRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionReadWithDefaults() *ConnectionRead {
	this := ConnectionRead{}
	var namespaceDefinition NamespaceDefinitionType = NAMESPACEDEFINITIONTYPE_SOURCE
	this.NamespaceDefinition = &namespaceDefinition
	var namespaceFormat string = "null"
	this.NamespaceFormat = &namespaceFormat
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *ConnectionRead) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetConnectionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *ConnectionRead) SetConnectionId(v string) {
	o.ConnectionId = v
}

// GetName returns the Name field value
func (o *ConnectionRead) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectionRead) SetName(v string) {
	o.Name = v
}

// GetNamespaceDefinition returns the NamespaceDefinition field value if set, zero value otherwise.
func (o *ConnectionRead) GetNamespaceDefinition() NamespaceDefinitionType {
	if o == nil || o.NamespaceDefinition == nil {
		var ret NamespaceDefinitionType
		return ret
	}
	return *o.NamespaceDefinition
}

// GetNamespaceDefinitionOk returns a tuple with the NamespaceDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetNamespaceDefinitionOk() (*NamespaceDefinitionType, bool) {
	if o == nil || o.NamespaceDefinition == nil {
		return nil, false
	}
	return o.NamespaceDefinition, true
}

// HasNamespaceDefinition returns a boolean if a field has been set.
func (o *ConnectionRead) HasNamespaceDefinition() bool {
	if o != nil && o.NamespaceDefinition != nil {
		return true
	}

	return false
}

// SetNamespaceDefinition gets a reference to the given NamespaceDefinitionType and assigns it to the NamespaceDefinition field.
func (o *ConnectionRead) SetNamespaceDefinition(v NamespaceDefinitionType) {
	o.NamespaceDefinition = &v
}

// GetNamespaceFormat returns the NamespaceFormat field value if set, zero value otherwise.
func (o *ConnectionRead) GetNamespaceFormat() string {
	if o == nil || o.NamespaceFormat == nil {
		var ret string
		return ret
	}
	return *o.NamespaceFormat
}

// GetNamespaceFormatOk returns a tuple with the NamespaceFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetNamespaceFormatOk() (*string, bool) {
	if o == nil || o.NamespaceFormat == nil {
		return nil, false
	}
	return o.NamespaceFormat, true
}

// HasNamespaceFormat returns a boolean if a field has been set.
func (o *ConnectionRead) HasNamespaceFormat() bool {
	if o != nil && o.NamespaceFormat != nil {
		return true
	}

	return false
}

// SetNamespaceFormat gets a reference to the given string and assigns it to the NamespaceFormat field.
func (o *ConnectionRead) SetNamespaceFormat(v string) {
	o.NamespaceFormat = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *ConnectionRead) GetPrefix() string {
	if o == nil || o.Prefix == nil {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetPrefixOk() (*string, bool) {
	if o == nil || o.Prefix == nil {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *ConnectionRead) HasPrefix() bool {
	if o != nil && o.Prefix != nil {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *ConnectionRead) SetPrefix(v string) {
	o.Prefix = &v
}

// GetSourceId returns the SourceId field value
func (o *ConnectionRead) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetSourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *ConnectionRead) SetSourceId(v string) {
	o.SourceId = v
}

// GetDestinationId returns the DestinationId field value
func (o *ConnectionRead) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetDestinationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *ConnectionRead) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetOperationIds returns the OperationIds field value if set, zero value otherwise.
func (o *ConnectionRead) GetOperationIds() []string {
	if o == nil || o.OperationIds == nil {
		var ret []string
		return ret
	}
	return o.OperationIds
}

// GetOperationIdsOk returns a tuple with the OperationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetOperationIdsOk() ([]string, bool) {
	if o == nil || o.OperationIds == nil {
		return nil, false
	}
	return o.OperationIds, true
}

// HasOperationIds returns a boolean if a field has been set.
func (o *ConnectionRead) HasOperationIds() bool {
	if o != nil && o.OperationIds != nil {
		return true
	}

	return false
}

// SetOperationIds gets a reference to the given []string and assigns it to the OperationIds field.
func (o *ConnectionRead) SetOperationIds(v []string) {
	o.OperationIds = v
}

// GetSyncCatalog returns the SyncCatalog field value
func (o *ConnectionRead) GetSyncCatalog() AirbyteCatalog {
	if o == nil {
		var ret AirbyteCatalog
		return ret
	}

	return o.SyncCatalog
}

// GetSyncCatalogOk returns a tuple with the SyncCatalog field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetSyncCatalogOk() (*AirbyteCatalog, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SyncCatalog, true
}

// SetSyncCatalog sets field value
func (o *ConnectionRead) SetSyncCatalog(v AirbyteCatalog) {
	o.SyncCatalog = v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConnectionRead) GetSchedule() ConnectionSchedule {
	if o == nil  {
		var ret ConnectionSchedule
		return ret
	}
	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConnectionRead) GetScheduleOk() (*ConnectionSchedule, bool) {
	if o == nil || o.Schedule == (ConnectionSchedule{}) {
		return nil, false
	}
	return &o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *ConnectionRead) HasSchedule() bool {
	if o != nil && o.Schedule != (ConnectionSchedule{}) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given ConnectionSchedule and assigns it to the Schedule field.
func (o *ConnectionRead) SetSchedule(v ConnectionSchedule) {
	o.Schedule = v
}

// GetStatus returns the Status field value
func (o *ConnectionRead) GetStatus() ConnectionStatus {
	if o == nil {
		var ret ConnectionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetStatusOk() (*ConnectionStatus, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ConnectionRead) SetStatus(v ConnectionStatus) {
	o.Status = v
}

// GetResourceRequirements returns the ResourceRequirements field value if set, zero value otherwise.
func (o *ConnectionRead) GetResourceRequirements() ResourceRequirements {
	if o == nil || o.ResourceRequirements == nil {
		var ret ResourceRequirements
		return ret
	}
	return *o.ResourceRequirements
}

// GetResourceRequirementsOk returns a tuple with the ResourceRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionRead) GetResourceRequirementsOk() (*ResourceRequirements, bool) {
	if o == nil || o.ResourceRequirements == nil {
		return nil, false
	}
	return o.ResourceRequirements, true
}

// HasResourceRequirements returns a boolean if a field has been set.
func (o *ConnectionRead) HasResourceRequirements() bool {
	if o != nil && o.ResourceRequirements != nil {
		return true
	}

	return false
}

// SetResourceRequirements gets a reference to the given ResourceRequirements and assigns it to the ResourceRequirements field.
func (o *ConnectionRead) SetResourceRequirements(v ResourceRequirements) {
	o.ResourceRequirements = &v
}

func (o ConnectionRead) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["connectionId"] = o.ConnectionId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.NamespaceDefinition != nil {
		toSerialize["namespaceDefinition"] = o.NamespaceDefinition
	}
	if o.NamespaceFormat != nil {
		toSerialize["namespaceFormat"] = o.NamespaceFormat
	}
	if o.Prefix != nil {
		toSerialize["prefix"] = o.Prefix
	}
	if true {
		toSerialize["sourceId"] = o.SourceId
	}
	if true {
		toSerialize["destinationId"] = o.DestinationId
	}
	if o.OperationIds != nil {
		toSerialize["operationIds"] = o.OperationIds
	}
	if true {
		toSerialize["syncCatalog"] = o.SyncCatalog
	}
	if o.Schedule != (ConnectionSchedule{}) {
		toSerialize["schedule"] = o.Schedule
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.ResourceRequirements != nil {
		toSerialize["resourceRequirements"] = o.ResourceRequirements
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionRead struct {
	value *ConnectionRead
	isSet bool
}

func (v NullableConnectionRead) Get() *ConnectionRead {
	return v.value
}

func (v *NullableConnectionRead) Set(val *ConnectionRead) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionRead) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionRead(val *ConnectionRead) *NullableConnectionRead {
	return &NullableConnectionRead{value: val, isSet: true}
}

func (v NullableConnectionRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


