/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// SourceUpdate struct for SourceUpdate
type SourceUpdate struct {
	SourceId string `json:"sourceId"`
	// The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
	ConnectionConfiguration interface{} `json:"connectionConfiguration"`
	Name string `json:"name"`
}

// NewSourceUpdate instantiates a new SourceUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceUpdate(sourceId string, connectionConfiguration interface{}, name string) *SourceUpdate {
	this := SourceUpdate{}
	this.SourceId = sourceId
	this.ConnectionConfiguration = connectionConfiguration
	this.Name = name
	return &this
}

// NewSourceUpdateWithDefaults instantiates a new SourceUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceUpdateWithDefaults() *SourceUpdate {
	this := SourceUpdate{}
	return &this
}

// GetSourceId returns the SourceId field value
func (o *SourceUpdate) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *SourceUpdate) GetSourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *SourceUpdate) SetSourceId(v string) {
	o.SourceId = v
}

// GetConnectionConfiguration returns the ConnectionConfiguration field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SourceUpdate) GetConnectionConfiguration() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ConnectionConfiguration
}

// GetConnectionConfigurationOk returns a tuple with the ConnectionConfiguration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceUpdate) GetConnectionConfigurationOk() (*interface{}, bool) {
	if o == nil || o.ConnectionConfiguration == nil {
		return nil, false
	}
	return &o.ConnectionConfiguration, true
}

// SetConnectionConfiguration sets field value
func (o *SourceUpdate) SetConnectionConfiguration(v interface{}) {
	o.ConnectionConfiguration = v
}

// GetName returns the Name field value
func (o *SourceUpdate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SourceUpdate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SourceUpdate) SetName(v string) {
	o.Name = v
}

func (o SourceUpdate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sourceId"] = o.SourceId
	}
	if o.ConnectionConfiguration != nil {
		toSerialize["connectionConfiguration"] = o.ConnectionConfiguration
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSourceUpdate struct {
	value *SourceUpdate
	isSet bool
}

func (v NullableSourceUpdate) Get() *SourceUpdate {
	return v.value
}

func (v *NullableSourceUpdate) Set(val *SourceUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceUpdate(val *SourceUpdate) *NullableSourceUpdate {
	return &NullableSourceUpdate{value: val, isSet: true}
}

func (v NullableSourceUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


