/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// WebBackendConnectionRequestBody struct for WebBackendConnectionRequestBody
type WebBackendConnectionRequestBody struct {
	WithRefreshedCatalog *bool `json:"withRefreshedCatalog,omitempty"`
	ConnectionId string `json:"connectionId"`
}

// NewWebBackendConnectionRequestBody instantiates a new WebBackendConnectionRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebBackendConnectionRequestBody(connectionId string) *WebBackendConnectionRequestBody {
	this := WebBackendConnectionRequestBody{}
	this.ConnectionId = connectionId
	return &this
}

// NewWebBackendConnectionRequestBodyWithDefaults instantiates a new WebBackendConnectionRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebBackendConnectionRequestBodyWithDefaults() *WebBackendConnectionRequestBody {
	this := WebBackendConnectionRequestBody{}
	return &this
}

// GetWithRefreshedCatalog returns the WithRefreshedCatalog field value if set, zero value otherwise.
func (o *WebBackendConnectionRequestBody) GetWithRefreshedCatalog() bool {
	if o == nil || o.WithRefreshedCatalog == nil {
		var ret bool
		return ret
	}
	return *o.WithRefreshedCatalog
}

// GetWithRefreshedCatalogOk returns a tuple with the WithRefreshedCatalog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRequestBody) GetWithRefreshedCatalogOk() (*bool, bool) {
	if o == nil || o.WithRefreshedCatalog == nil {
		return nil, false
	}
	return o.WithRefreshedCatalog, true
}

// HasWithRefreshedCatalog returns a boolean if a field has been set.
func (o *WebBackendConnectionRequestBody) HasWithRefreshedCatalog() bool {
	if o != nil && o.WithRefreshedCatalog != nil {
		return true
	}

	return false
}

// SetWithRefreshedCatalog gets a reference to the given bool and assigns it to the WithRefreshedCatalog field.
func (o *WebBackendConnectionRequestBody) SetWithRefreshedCatalog(v bool) {
	o.WithRefreshedCatalog = &v
}

// GetConnectionId returns the ConnectionId field value
func (o *WebBackendConnectionRequestBody) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRequestBody) GetConnectionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *WebBackendConnectionRequestBody) SetConnectionId(v string) {
	o.ConnectionId = v
}

func (o WebBackendConnectionRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.WithRefreshedCatalog != nil {
		toSerialize["withRefreshedCatalog"] = o.WithRefreshedCatalog
	}
	if true {
		toSerialize["connectionId"] = o.ConnectionId
	}
	return json.Marshal(toSerialize)
}

type NullableWebBackendConnectionRequestBody struct {
	value *WebBackendConnectionRequestBody
	isSet bool
}

func (v NullableWebBackendConnectionRequestBody) Get() *WebBackendConnectionRequestBody {
	return v.value
}

func (v *NullableWebBackendConnectionRequestBody) Set(val *WebBackendConnectionRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableWebBackendConnectionRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableWebBackendConnectionRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebBackendConnectionRequestBody(val *WebBackendConnectionRequestBody) *NullableWebBackendConnectionRequestBody {
	return &NullableWebBackendConnectionRequestBody{value: val, isSet: true}
}

func (v NullableWebBackendConnectionRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebBackendConnectionRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


