/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// LogsRequestBody struct for LogsRequestBody
type LogsRequestBody struct {
	LogType LogType `json:"logType"`
}

// NewLogsRequestBody instantiates a new LogsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogsRequestBody(logType LogType) *LogsRequestBody {
	this := LogsRequestBody{}
	this.LogType = logType
	return &this
}

// NewLogsRequestBodyWithDefaults instantiates a new LogsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogsRequestBodyWithDefaults() *LogsRequestBody {
	this := LogsRequestBody{}
	return &this
}

// GetLogType returns the LogType field value
func (o *LogsRequestBody) GetLogType() LogType {
	if o == nil {
		var ret LogType
		return ret
	}

	return o.LogType
}

// GetLogTypeOk returns a tuple with the LogType field value
// and a boolean to check if the value has been set.
func (o *LogsRequestBody) GetLogTypeOk() (*LogType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LogType, true
}

// SetLogType sets field value
func (o *LogsRequestBody) SetLogType(v LogType) {
	o.LogType = v
}

func (o LogsRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["logType"] = o.LogType
	}
	return json.Marshal(toSerialize)
}

type NullableLogsRequestBody struct {
	value *LogsRequestBody
	isSet bool
}

func (v NullableLogsRequestBody) Get() *LogsRequestBody {
	return v.value
}

func (v *NullableLogsRequestBody) Set(val *LogsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLogsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLogsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogsRequestBody(val *LogsRequestBody) *NullableLogsRequestBody {
	return &NullableLogsRequestBody{value: val, isSet: true}
}

func (v NullableLogsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


