/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
	"fmt"
)

// NamespaceDefinitionType Method used for computing final namespace in destination
type NamespaceDefinitionType string

// List of NamespaceDefinitionType
const (
	NAMESPACEDEFINITIONTYPE_SOURCE NamespaceDefinitionType = "source"
	NAMESPACEDEFINITIONTYPE_DESTINATION NamespaceDefinitionType = "destination"
	NAMESPACEDEFINITIONTYPE_CUSTOMFORMAT NamespaceDefinitionType = "customformat"
)

// All allowed values of NamespaceDefinitionType enum
var AllowedNamespaceDefinitionTypeEnumValues = []NamespaceDefinitionType{
	"source",
	"destination",
	"customformat",
}

func (v *NamespaceDefinitionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NamespaceDefinitionType(value)
	for _, existing := range AllowedNamespaceDefinitionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NamespaceDefinitionType", value)
}

// NewNamespaceDefinitionTypeFromValue returns a pointer to a valid NamespaceDefinitionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNamespaceDefinitionTypeFromValue(v string) (*NamespaceDefinitionType, error) {
	ev := NamespaceDefinitionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NamespaceDefinitionType: valid values are %v", v, AllowedNamespaceDefinitionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NamespaceDefinitionType) IsValid() bool {
	for _, existing := range AllowedNamespaceDefinitionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to NamespaceDefinitionType value
func (v NamespaceDefinitionType) Ptr() *NamespaceDefinitionType {
	return &v
}

type NullableNamespaceDefinitionType struct {
	value *NamespaceDefinitionType
	isSet bool
}

func (v NullableNamespaceDefinitionType) Get() *NamespaceDefinitionType {
	return v.value
}

func (v *NullableNamespaceDefinitionType) Set(val *NamespaceDefinitionType) {
	v.value = val
	v.isSet = true
}

func (v NullableNamespaceDefinitionType) IsSet() bool {
	return v.isSet
}

func (v *NullableNamespaceDefinitionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNamespaceDefinitionType(val *NamespaceDefinitionType) *NullableNamespaceDefinitionType {
	return &NullableNamespaceDefinitionType{value: val, isSet: true}
}

func (v NullableNamespaceDefinitionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNamespaceDefinitionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

