/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// DestinationDefinitionReadList struct for DestinationDefinitionReadList
type DestinationDefinitionReadList struct {
	DestinationDefinitions []DestinationDefinitionRead `json:"destinationDefinitions"`
}

// NewDestinationDefinitionReadList instantiates a new DestinationDefinitionReadList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestinationDefinitionReadList(destinationDefinitions []DestinationDefinitionRead) *DestinationDefinitionReadList {
	this := DestinationDefinitionReadList{}
	this.DestinationDefinitions = destinationDefinitions
	return &this
}

// NewDestinationDefinitionReadListWithDefaults instantiates a new DestinationDefinitionReadList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestinationDefinitionReadListWithDefaults() *DestinationDefinitionReadList {
	this := DestinationDefinitionReadList{}
	return &this
}

// GetDestinationDefinitions returns the DestinationDefinitions field value
func (o *DestinationDefinitionReadList) GetDestinationDefinitions() []DestinationDefinitionRead {
	if o == nil {
		var ret []DestinationDefinitionRead
		return ret
	}

	return o.DestinationDefinitions
}

// GetDestinationDefinitionsOk returns a tuple with the DestinationDefinitions field value
// and a boolean to check if the value has been set.
func (o *DestinationDefinitionReadList) GetDestinationDefinitionsOk() ([]DestinationDefinitionRead, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DestinationDefinitions, true
}

// SetDestinationDefinitions sets field value
func (o *DestinationDefinitionReadList) SetDestinationDefinitions(v []DestinationDefinitionRead) {
	o.DestinationDefinitions = v
}

func (o DestinationDefinitionReadList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["destinationDefinitions"] = o.DestinationDefinitions
	}
	return json.Marshal(toSerialize)
}

type NullableDestinationDefinitionReadList struct {
	value *DestinationDefinitionReadList
	isSet bool
}

func (v NullableDestinationDefinitionReadList) Get() *DestinationDefinitionReadList {
	return v.value
}

func (v *NullableDestinationDefinitionReadList) Set(val *DestinationDefinitionReadList) {
	v.value = val
	v.isSet = true
}

func (v NullableDestinationDefinitionReadList) IsSet() bool {
	return v.isSet
}

func (v *NullableDestinationDefinitionReadList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestinationDefinitionReadList(val *DestinationDefinitionReadList) *NullableDestinationDefinitionReadList {
	return &NullableDestinationDefinitionReadList{value: val, isSet: true}
}

func (v NullableDestinationDefinitionReadList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestinationDefinitionReadList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


