/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// WebBackendConnectionRead struct for WebBackendConnectionRead
type WebBackendConnectionRead struct {
	ConnectionId string `json:"connectionId"`
	Name string `json:"name"`
	NamespaceDefinition *NamespaceDefinitionType `json:"namespaceDefinition,omitempty"`
	// Used when namespaceDefinition is 'customformat'. If blank then behaves like namespaceDefinition = 'destination'. If \"${SOURCE_NAMESPACE}\" then behaves like namespaceDefinition = 'source'.
	NamespaceFormat *string `json:"namespaceFormat,omitempty"`
	// Prefix that will be prepended to the name of each stream when it is written to the destination.
	Prefix *string `json:"prefix,omitempty"`
	SourceId string `json:"sourceId"`
	DestinationId string `json:"destinationId"`
	SyncCatalog AirbyteCatalog `json:"syncCatalog"`
	Schedule *ConnectionSchedule `json:"schedule,omitempty"`
	Status ConnectionStatus `json:"status"`
	OperationIds []string `json:"operationIds,omitempty"`
	Source SourceRead `json:"source"`
	Destination DestinationRead `json:"destination"`
	Operations []OperationRead `json:"operations,omitempty"`
	// epoch time of the latest sync job. null if no sync job has taken place.
	LatestSyncJobCreatedAt *int64 `json:"latestSyncJobCreatedAt,omitempty"`
	LatestSyncJobStatus *JobStatus `json:"latestSyncJobStatus,omitempty"`
	IsSyncing bool `json:"isSyncing"`
	ResourceRequirements *ResourceRequirements `json:"resourceRequirements,omitempty"`
}

// NewWebBackendConnectionRead instantiates a new WebBackendConnectionRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebBackendConnectionRead(connectionId string, name string, sourceId string, destinationId string, syncCatalog AirbyteCatalog, status ConnectionStatus, source SourceRead, destination DestinationRead, isSyncing bool) *WebBackendConnectionRead {
	this := WebBackendConnectionRead{}
	this.ConnectionId = connectionId
	this.Name = name
	var namespaceDefinition NamespaceDefinitionType = NAMESPACEDEFINITIONTYPE_SOURCE
	this.NamespaceDefinition = &namespaceDefinition
	var namespaceFormat string = "null"
	this.NamespaceFormat = &namespaceFormat
	this.SourceId = sourceId
	this.DestinationId = destinationId
	this.SyncCatalog = syncCatalog
	this.Status = status
	this.Source = source
	this.Destination = destination
	this.IsSyncing = isSyncing
	return &this
}

// NewWebBackendConnectionReadWithDefaults instantiates a new WebBackendConnectionRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebBackendConnectionReadWithDefaults() *WebBackendConnectionRead {
	this := WebBackendConnectionRead{}
	var namespaceDefinition NamespaceDefinitionType = NAMESPACEDEFINITIONTYPE_SOURCE
	this.NamespaceDefinition = &namespaceDefinition
	var namespaceFormat string = "null"
	this.NamespaceFormat = &namespaceFormat
	return &this
}

// GetConnectionId returns the ConnectionId field value
func (o *WebBackendConnectionRead) GetConnectionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetConnectionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConnectionId, true
}

// SetConnectionId sets field value
func (o *WebBackendConnectionRead) SetConnectionId(v string) {
	o.ConnectionId = v
}

// GetName returns the Name field value
func (o *WebBackendConnectionRead) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WebBackendConnectionRead) SetName(v string) {
	o.Name = v
}

// GetNamespaceDefinition returns the NamespaceDefinition field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetNamespaceDefinition() NamespaceDefinitionType {
	if o == nil || o.NamespaceDefinition == nil {
		var ret NamespaceDefinitionType
		return ret
	}
	return *o.NamespaceDefinition
}

// GetNamespaceDefinitionOk returns a tuple with the NamespaceDefinition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetNamespaceDefinitionOk() (*NamespaceDefinitionType, bool) {
	if o == nil || o.NamespaceDefinition == nil {
		return nil, false
	}
	return o.NamespaceDefinition, true
}

// HasNamespaceDefinition returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasNamespaceDefinition() bool {
	if o != nil && o.NamespaceDefinition != nil {
		return true
	}

	return false
}

// SetNamespaceDefinition gets a reference to the given NamespaceDefinitionType and assigns it to the NamespaceDefinition field.
func (o *WebBackendConnectionRead) SetNamespaceDefinition(v NamespaceDefinitionType) {
	o.NamespaceDefinition = &v
}

// GetNamespaceFormat returns the NamespaceFormat field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetNamespaceFormat() string {
	if o == nil || o.NamespaceFormat == nil {
		var ret string
		return ret
	}
	return *o.NamespaceFormat
}

// GetNamespaceFormatOk returns a tuple with the NamespaceFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetNamespaceFormatOk() (*string, bool) {
	if o == nil || o.NamespaceFormat == nil {
		return nil, false
	}
	return o.NamespaceFormat, true
}

// HasNamespaceFormat returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasNamespaceFormat() bool {
	if o != nil && o.NamespaceFormat != nil {
		return true
	}

	return false
}

// SetNamespaceFormat gets a reference to the given string and assigns it to the NamespaceFormat field.
func (o *WebBackendConnectionRead) SetNamespaceFormat(v string) {
	o.NamespaceFormat = &v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetPrefix() string {
	if o == nil || o.Prefix == nil {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetPrefixOk() (*string, bool) {
	if o == nil || o.Prefix == nil {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasPrefix() bool {
	if o != nil && o.Prefix != nil {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *WebBackendConnectionRead) SetPrefix(v string) {
	o.Prefix = &v
}

// GetSourceId returns the SourceId field value
func (o *WebBackendConnectionRead) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetSourceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *WebBackendConnectionRead) SetSourceId(v string) {
	o.SourceId = v
}

// GetDestinationId returns the DestinationId field value
func (o *WebBackendConnectionRead) GetDestinationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationId
}

// GetDestinationIdOk returns a tuple with the DestinationId field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetDestinationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DestinationId, true
}

// SetDestinationId sets field value
func (o *WebBackendConnectionRead) SetDestinationId(v string) {
	o.DestinationId = v
}

// GetSyncCatalog returns the SyncCatalog field value
func (o *WebBackendConnectionRead) GetSyncCatalog() AirbyteCatalog {
	if o == nil {
		var ret AirbyteCatalog
		return ret
	}

	return o.SyncCatalog
}

// GetSyncCatalogOk returns a tuple with the SyncCatalog field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetSyncCatalogOk() (*AirbyteCatalog, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SyncCatalog, true
}

// SetSyncCatalog sets field value
func (o *WebBackendConnectionRead) SetSyncCatalog(v AirbyteCatalog) {
	o.SyncCatalog = v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetSchedule() ConnectionSchedule {
	if o == nil || o.Schedule == nil {
		var ret ConnectionSchedule
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetScheduleOk() (*ConnectionSchedule, bool) {
	if o == nil || o.Schedule == nil {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasSchedule() bool {
	if o != nil && o.Schedule != nil {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given ConnectionSchedule and assigns it to the Schedule field.
func (o *WebBackendConnectionRead) SetSchedule(v ConnectionSchedule) {
	o.Schedule = &v
}

// GetStatus returns the Status field value
func (o *WebBackendConnectionRead) GetStatus() ConnectionStatus {
	if o == nil {
		var ret ConnectionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetStatusOk() (*ConnectionStatus, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WebBackendConnectionRead) SetStatus(v ConnectionStatus) {
	o.Status = v
}

// GetOperationIds returns the OperationIds field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetOperationIds() []string {
	if o == nil || o.OperationIds == nil {
		var ret []string
		return ret
	}
	return o.OperationIds
}

// GetOperationIdsOk returns a tuple with the OperationIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetOperationIdsOk() ([]string, bool) {
	if o == nil || o.OperationIds == nil {
		return nil, false
	}
	return o.OperationIds, true
}

// HasOperationIds returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasOperationIds() bool {
	if o != nil && o.OperationIds != nil {
		return true
	}

	return false
}

// SetOperationIds gets a reference to the given []string and assigns it to the OperationIds field.
func (o *WebBackendConnectionRead) SetOperationIds(v []string) {
	o.OperationIds = v
}

// GetSource returns the Source field value
func (o *WebBackendConnectionRead) GetSource() SourceRead {
	if o == nil {
		var ret SourceRead
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetSourceOk() (*SourceRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *WebBackendConnectionRead) SetSource(v SourceRead) {
	o.Source = v
}

// GetDestination returns the Destination field value
func (o *WebBackendConnectionRead) GetDestination() DestinationRead {
	if o == nil {
		var ret DestinationRead
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetDestinationOk() (*DestinationRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *WebBackendConnectionRead) SetDestination(v DestinationRead) {
	o.Destination = v
}

// GetOperations returns the Operations field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetOperations() []OperationRead {
	if o == nil || o.Operations == nil {
		var ret []OperationRead
		return ret
	}
	return o.Operations
}

// GetOperationsOk returns a tuple with the Operations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetOperationsOk() ([]OperationRead, bool) {
	if o == nil || o.Operations == nil {
		return nil, false
	}
	return o.Operations, true
}

// HasOperations returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasOperations() bool {
	if o != nil && o.Operations != nil {
		return true
	}

	return false
}

// SetOperations gets a reference to the given []OperationRead and assigns it to the Operations field.
func (o *WebBackendConnectionRead) SetOperations(v []OperationRead) {
	o.Operations = v
}

// GetLatestSyncJobCreatedAt returns the LatestSyncJobCreatedAt field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetLatestSyncJobCreatedAt() int64 {
	if o == nil || o.LatestSyncJobCreatedAt == nil {
		var ret int64
		return ret
	}
	return *o.LatestSyncJobCreatedAt
}

// GetLatestSyncJobCreatedAtOk returns a tuple with the LatestSyncJobCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetLatestSyncJobCreatedAtOk() (*int64, bool) {
	if o == nil || o.LatestSyncJobCreatedAt == nil {
		return nil, false
	}
	return o.LatestSyncJobCreatedAt, true
}

// HasLatestSyncJobCreatedAt returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasLatestSyncJobCreatedAt() bool {
	if o != nil && o.LatestSyncJobCreatedAt != nil {
		return true
	}

	return false
}

// SetLatestSyncJobCreatedAt gets a reference to the given int64 and assigns it to the LatestSyncJobCreatedAt field.
func (o *WebBackendConnectionRead) SetLatestSyncJobCreatedAt(v int64) {
	o.LatestSyncJobCreatedAt = &v
}

// GetLatestSyncJobStatus returns the LatestSyncJobStatus field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetLatestSyncJobStatus() JobStatus {
	if o == nil || o.LatestSyncJobStatus == nil {
		var ret JobStatus
		return ret
	}
	return *o.LatestSyncJobStatus
}

// GetLatestSyncJobStatusOk returns a tuple with the LatestSyncJobStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetLatestSyncJobStatusOk() (*JobStatus, bool) {
	if o == nil || o.LatestSyncJobStatus == nil {
		return nil, false
	}
	return o.LatestSyncJobStatus, true
}

// HasLatestSyncJobStatus returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasLatestSyncJobStatus() bool {
	if o != nil && o.LatestSyncJobStatus != nil {
		return true
	}

	return false
}

// SetLatestSyncJobStatus gets a reference to the given JobStatus and assigns it to the LatestSyncJobStatus field.
func (o *WebBackendConnectionRead) SetLatestSyncJobStatus(v JobStatus) {
	o.LatestSyncJobStatus = &v
}

// GetIsSyncing returns the IsSyncing field value
func (o *WebBackendConnectionRead) GetIsSyncing() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSyncing
}

// GetIsSyncingOk returns a tuple with the IsSyncing field value
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetIsSyncingOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsSyncing, true
}

// SetIsSyncing sets field value
func (o *WebBackendConnectionRead) SetIsSyncing(v bool) {
	o.IsSyncing = v
}

// GetResourceRequirements returns the ResourceRequirements field value if set, zero value otherwise.
func (o *WebBackendConnectionRead) GetResourceRequirements() ResourceRequirements {
	if o == nil || o.ResourceRequirements == nil {
		var ret ResourceRequirements
		return ret
	}
	return *o.ResourceRequirements
}

// GetResourceRequirementsOk returns a tuple with the ResourceRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebBackendConnectionRead) GetResourceRequirementsOk() (*ResourceRequirements, bool) {
	if o == nil || o.ResourceRequirements == nil {
		return nil, false
	}
	return o.ResourceRequirements, true
}

// HasResourceRequirements returns a boolean if a field has been set.
func (o *WebBackendConnectionRead) HasResourceRequirements() bool {
	if o != nil && o.ResourceRequirements != nil {
		return true
	}

	return false
}

// SetResourceRequirements gets a reference to the given ResourceRequirements and assigns it to the ResourceRequirements field.
func (o *WebBackendConnectionRead) SetResourceRequirements(v ResourceRequirements) {
	o.ResourceRequirements = &v
}

func (o WebBackendConnectionRead) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["connectionId"] = o.ConnectionId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.NamespaceDefinition != nil {
		toSerialize["namespaceDefinition"] = o.NamespaceDefinition
	}
	if o.NamespaceFormat != nil {
		toSerialize["namespaceFormat"] = o.NamespaceFormat
	}
	if o.Prefix != nil {
		toSerialize["prefix"] = o.Prefix
	}
	if true {
		toSerialize["sourceId"] = o.SourceId
	}
	if true {
		toSerialize["destinationId"] = o.DestinationId
	}
	if true {
		toSerialize["syncCatalog"] = o.SyncCatalog
	}
	if o.Schedule != nil {
		toSerialize["schedule"] = o.Schedule
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.OperationIds != nil {
		toSerialize["operationIds"] = o.OperationIds
	}
	if true {
		toSerialize["source"] = o.Source
	}
	if true {
		toSerialize["destination"] = o.Destination
	}
	if o.Operations != nil {
		toSerialize["operations"] = o.Operations
	}
	if o.LatestSyncJobCreatedAt != nil {
		toSerialize["latestSyncJobCreatedAt"] = o.LatestSyncJobCreatedAt
	}
	if o.LatestSyncJobStatus != nil {
		toSerialize["latestSyncJobStatus"] = o.LatestSyncJobStatus
	}
	if true {
		toSerialize["isSyncing"] = o.IsSyncing
	}
	if o.ResourceRequirements != nil {
		toSerialize["resourceRequirements"] = o.ResourceRequirements
	}
	return json.Marshal(toSerialize)
}

type NullableWebBackendConnectionRead struct {
	value *WebBackendConnectionRead
	isSet bool
}

func (v NullableWebBackendConnectionRead) Get() *WebBackendConnectionRead {
	return v.value
}

func (v *NullableWebBackendConnectionRead) Set(val *WebBackendConnectionRead) {
	v.value = val
	v.isSet = true
}

func (v NullableWebBackendConnectionRead) IsSet() bool {
	return v.isSet
}

func (v *NullableWebBackendConnectionRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebBackendConnectionRead(val *WebBackendConnectionRead) *NullableWebBackendConnectionRead {
	return &NullableWebBackendConnectionRead{value: val, isSet: true}
}

func (v NullableWebBackendConnectionRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebBackendConnectionRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


