/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// SourceCreate struct for SourceCreate
type SourceCreate struct {
	SourceDefinitionId string `json:"sourceDefinitionId"`
	// The values required to configure the source. The schema for this must match the schema return by source_definition_specifications/get for the source.
	ConnectionConfiguration interface{} `json:"connectionConfiguration"`
	WorkspaceId string `json:"workspaceId"`
	Name string `json:"name"`
}

// NewSourceCreate instantiates a new SourceCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceCreate(sourceDefinitionId string, connectionConfiguration interface{}, workspaceId string, name string) *SourceCreate {
	this := SourceCreate{}
	this.SourceDefinitionId = sourceDefinitionId
	this.ConnectionConfiguration = connectionConfiguration
	this.WorkspaceId = workspaceId
	this.Name = name
	return &this
}

// NewSourceCreateWithDefaults instantiates a new SourceCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceCreateWithDefaults() *SourceCreate {
	this := SourceCreate{}
	return &this
}

// GetSourceDefinitionId returns the SourceDefinitionId field value
func (o *SourceCreate) GetSourceDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceDefinitionId
}

// GetSourceDefinitionIdOk returns a tuple with the SourceDefinitionId field value
// and a boolean to check if the value has been set.
func (o *SourceCreate) GetSourceDefinitionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceDefinitionId, true
}

// SetSourceDefinitionId sets field value
func (o *SourceCreate) SetSourceDefinitionId(v string) {
	o.SourceDefinitionId = v
}

// GetConnectionConfiguration returns the ConnectionConfiguration field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *SourceCreate) GetConnectionConfiguration() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ConnectionConfiguration
}

// GetConnectionConfigurationOk returns a tuple with the ConnectionConfiguration field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceCreate) GetConnectionConfigurationOk() (*interface{}, bool) {
	if o == nil || o.ConnectionConfiguration == nil {
		return nil, false
	}
	return &o.ConnectionConfiguration, true
}

// SetConnectionConfiguration sets field value
func (o *SourceCreate) SetConnectionConfiguration(v interface{}) {
	o.ConnectionConfiguration = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *SourceCreate) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *SourceCreate) GetWorkspaceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *SourceCreate) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetName returns the Name field value
func (o *SourceCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SourceCreate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SourceCreate) SetName(v string) {
	o.Name = v
}

func (o SourceCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sourceDefinitionId"] = o.SourceDefinitionId
	}
	if o.ConnectionConfiguration != nil {
		toSerialize["connectionConfiguration"] = o.ConnectionConfiguration
	}
	if true {
		toSerialize["workspaceId"] = o.WorkspaceId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableSourceCreate struct {
	value *SourceCreate
	isSet bool
}

func (v NullableSourceCreate) Get() *SourceCreate {
	return v.value
}

func (v *NullableSourceCreate) Set(val *SourceCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceCreate(val *SourceCreate) *NullableSourceCreate {
	return &NullableSourceCreate{value: val, isSet: true}
}

func (v NullableSourceCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


