/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// SourceOauthConsentRequest struct for SourceOauthConsentRequest
type SourceOauthConsentRequest struct {
	SourceDefinitionId string `json:"sourceDefinitionId"`
	WorkspaceId string `json:"workspaceId"`
	// The url to redirect to after getting the user consent
	RedirectUrl string `json:"redirectUrl"`
	// OAuth specific blob.
	OAuthInputConfiguration interface{} `json:"oAuthInputConfiguration,omitempty"`
}

// NewSourceOauthConsentRequest instantiates a new SourceOauthConsentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceOauthConsentRequest(sourceDefinitionId string, workspaceId string, redirectUrl string) *SourceOauthConsentRequest {
	this := SourceOauthConsentRequest{}
	this.SourceDefinitionId = sourceDefinitionId
	this.WorkspaceId = workspaceId
	this.RedirectUrl = redirectUrl
	return &this
}

// NewSourceOauthConsentRequestWithDefaults instantiates a new SourceOauthConsentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceOauthConsentRequestWithDefaults() *SourceOauthConsentRequest {
	this := SourceOauthConsentRequest{}
	return &this
}

// GetSourceDefinitionId returns the SourceDefinitionId field value
func (o *SourceOauthConsentRequest) GetSourceDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceDefinitionId
}

// GetSourceDefinitionIdOk returns a tuple with the SourceDefinitionId field value
// and a boolean to check if the value has been set.
func (o *SourceOauthConsentRequest) GetSourceDefinitionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SourceDefinitionId, true
}

// SetSourceDefinitionId sets field value
func (o *SourceOauthConsentRequest) SetSourceDefinitionId(v string) {
	o.SourceDefinitionId = v
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *SourceOauthConsentRequest) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *SourceOauthConsentRequest) GetWorkspaceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *SourceOauthConsentRequest) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetRedirectUrl returns the RedirectUrl field value
func (o *SourceOauthConsentRequest) GetRedirectUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value
// and a boolean to check if the value has been set.
func (o *SourceOauthConsentRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RedirectUrl, true
}

// SetRedirectUrl sets field value
func (o *SourceOauthConsentRequest) SetRedirectUrl(v string) {
	o.RedirectUrl = v
}

// GetOAuthInputConfiguration returns the OAuthInputConfiguration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SourceOauthConsentRequest) GetOAuthInputConfiguration() interface{} {
	if o == nil  {
		var ret interface{}
		return ret
	}
	return o.OAuthInputConfiguration
}

// GetOAuthInputConfigurationOk returns a tuple with the OAuthInputConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceOauthConsentRequest) GetOAuthInputConfigurationOk() (*interface{}, bool) {
	if o == nil || o.OAuthInputConfiguration == nil {
		return nil, false
	}
	return &o.OAuthInputConfiguration, true
}

// HasOAuthInputConfiguration returns a boolean if a field has been set.
func (o *SourceOauthConsentRequest) HasOAuthInputConfiguration() bool {
	if o != nil && o.OAuthInputConfiguration != nil {
		return true
	}

	return false
}

// SetOAuthInputConfiguration gets a reference to the given interface{} and assigns it to the OAuthInputConfiguration field.
func (o *SourceOauthConsentRequest) SetOAuthInputConfiguration(v interface{}) {
	o.OAuthInputConfiguration = v
}

func (o SourceOauthConsentRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["sourceDefinitionId"] = o.SourceDefinitionId
	}
	if true {
		toSerialize["workspaceId"] = o.WorkspaceId
	}
	if true {
		toSerialize["redirectUrl"] = o.RedirectUrl
	}
	if o.OAuthInputConfiguration != nil {
		toSerialize["oAuthInputConfiguration"] = o.OAuthInputConfiguration
	}
	return json.Marshal(toSerialize)
}

type NullableSourceOauthConsentRequest struct {
	value *SourceOauthConsentRequest
	isSet bool
}

func (v NullableSourceOauthConsentRequest) Get() *SourceOauthConsentRequest {
	return v.value
}

func (v *NullableSourceOauthConsentRequest) Set(val *SourceOauthConsentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceOauthConsentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceOauthConsentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceOauthConsentRequest(val *SourceOauthConsentRequest) *NullableSourceOauthConsentRequest {
	return &NullableSourceOauthConsentRequest{value: val, isSet: true}
}

func (v NullableSourceOauthConsentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceOauthConsentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


