/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// JobDebugInfoRead struct for JobDebugInfoRead
type JobDebugInfoRead struct {
	Job JobDebugRead `json:"job"`
	Attempts []AttemptInfoRead `json:"attempts"`
}

// NewJobDebugInfoRead instantiates a new JobDebugInfoRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobDebugInfoRead(job JobDebugRead, attempts []AttemptInfoRead) *JobDebugInfoRead {
	this := JobDebugInfoRead{}
	this.Job = job
	this.Attempts = attempts
	return &this
}

// NewJobDebugInfoReadWithDefaults instantiates a new JobDebugInfoRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobDebugInfoReadWithDefaults() *JobDebugInfoRead {
	this := JobDebugInfoRead{}
	return &this
}

// GetJob returns the Job field value
func (o *JobDebugInfoRead) GetJob() JobDebugRead {
	if o == nil {
		var ret JobDebugRead
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *JobDebugInfoRead) GetJobOk() (*JobDebugRead, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *JobDebugInfoRead) SetJob(v JobDebugRead) {
	o.Job = v
}

// GetAttempts returns the Attempts field value
func (o *JobDebugInfoRead) GetAttempts() []AttemptInfoRead {
	if o == nil {
		var ret []AttemptInfoRead
		return ret
	}

	return o.Attempts
}

// GetAttemptsOk returns a tuple with the Attempts field value
// and a boolean to check if the value has been set.
func (o *JobDebugInfoRead) GetAttemptsOk() ([]AttemptInfoRead, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Attempts, true
}

// SetAttempts sets field value
func (o *JobDebugInfoRead) SetAttempts(v []AttemptInfoRead) {
	o.Attempts = v
}

func (o JobDebugInfoRead) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["job"] = o.Job
	}
	if true {
		toSerialize["attempts"] = o.Attempts
	}
	return json.Marshal(toSerialize)
}

type NullableJobDebugInfoRead struct {
	value *JobDebugInfoRead
	isSet bool
}

func (v NullableJobDebugInfoRead) Get() *JobDebugInfoRead {
	return v.value
}

func (v *NullableJobDebugInfoRead) Set(val *JobDebugInfoRead) {
	v.value = val
	v.isSet = true
}

func (v NullableJobDebugInfoRead) IsSet() bool {
	return v.isSet
}

func (v *NullableJobDebugInfoRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobDebugInfoRead(val *JobDebugInfoRead) *NullableJobDebugInfoRead {
	return &NullableJobDebugInfoRead{value: val, isSet: true}
}

func (v NullableJobDebugInfoRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobDebugInfoRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


