/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// JobIdRequestBody struct for JobIdRequestBody
type JobIdRequestBody struct {
	Id int64 `json:"id"`
}

// NewJobIdRequestBody instantiates a new JobIdRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobIdRequestBody(id int64) *JobIdRequestBody {
	this := JobIdRequestBody{}
	this.Id = id
	return &this
}

// NewJobIdRequestBodyWithDefaults instantiates a new JobIdRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobIdRequestBodyWithDefaults() *JobIdRequestBody {
	this := JobIdRequestBody{}
	return &this
}

// GetId returns the Id field value
func (o *JobIdRequestBody) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobIdRequestBody) GetIdOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobIdRequestBody) SetId(v int64) {
	o.Id = v
}

func (o JobIdRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableJobIdRequestBody struct {
	value *JobIdRequestBody
	isSet bool
}

func (v NullableJobIdRequestBody) Get() *JobIdRequestBody {
	return v.value
}

func (v *NullableJobIdRequestBody) Set(val *JobIdRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableJobIdRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableJobIdRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobIdRequestBody(val *JobIdRequestBody) *NullableJobIdRequestBody {
	return &NullableJobIdRequestBody{value: val, isSet: true}
}

func (v NullableJobIdRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobIdRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


