/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// SetInstancewideDestinationOauthParamsRequestBody struct for SetInstancewideDestinationOauthParamsRequestBody
type SetInstancewideDestinationOauthParamsRequestBody struct {
	DestinationDefinitionId string `json:"destinationDefinitionId"`
	Params map[string]map[string]interface{} `json:"params"`
}

// NewSetInstancewideDestinationOauthParamsRequestBody instantiates a new SetInstancewideDestinationOauthParamsRequestBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetInstancewideDestinationOauthParamsRequestBody(destinationDefinitionId string, params map[string]map[string]interface{}) *SetInstancewideDestinationOauthParamsRequestBody {
	this := SetInstancewideDestinationOauthParamsRequestBody{}
	this.DestinationDefinitionId = destinationDefinitionId
	this.Params = params
	return &this
}

// NewSetInstancewideDestinationOauthParamsRequestBodyWithDefaults instantiates a new SetInstancewideDestinationOauthParamsRequestBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetInstancewideDestinationOauthParamsRequestBodyWithDefaults() *SetInstancewideDestinationOauthParamsRequestBody {
	this := SetInstancewideDestinationOauthParamsRequestBody{}
	return &this
}

// GetDestinationDefinitionId returns the DestinationDefinitionId field value
func (o *SetInstancewideDestinationOauthParamsRequestBody) GetDestinationDefinitionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestinationDefinitionId
}

// GetDestinationDefinitionIdOk returns a tuple with the DestinationDefinitionId field value
// and a boolean to check if the value has been set.
func (o *SetInstancewideDestinationOauthParamsRequestBody) GetDestinationDefinitionIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DestinationDefinitionId, true
}

// SetDestinationDefinitionId sets field value
func (o *SetInstancewideDestinationOauthParamsRequestBody) SetDestinationDefinitionId(v string) {
	o.DestinationDefinitionId = v
}

// GetParams returns the Params field value
func (o *SetInstancewideDestinationOauthParamsRequestBody) GetParams() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *SetInstancewideDestinationOauthParamsRequestBody) GetParamsOk() (map[string]map[string]interface{}, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Params, true
}

// SetParams sets field value
func (o *SetInstancewideDestinationOauthParamsRequestBody) SetParams(v map[string]map[string]interface{}) {
	o.Params = v
}

func (o SetInstancewideDestinationOauthParamsRequestBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["destinationDefinitionId"] = o.DestinationDefinitionId
	}
	if true {
		toSerialize["params"] = o.Params
	}
	return json.Marshal(toSerialize)
}

type NullableSetInstancewideDestinationOauthParamsRequestBody struct {
	value *SetInstancewideDestinationOauthParamsRequestBody
	isSet bool
}

func (v NullableSetInstancewideDestinationOauthParamsRequestBody) Get() *SetInstancewideDestinationOauthParamsRequestBody {
	return v.value
}

func (v *NullableSetInstancewideDestinationOauthParamsRequestBody) Set(val *SetInstancewideDestinationOauthParamsRequestBody) {
	v.value = val
	v.isSet = true
}

func (v NullableSetInstancewideDestinationOauthParamsRequestBody) IsSet() bool {
	return v.isSet
}

func (v *NullableSetInstancewideDestinationOauthParamsRequestBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetInstancewideDestinationOauthParamsRequestBody(val *SetInstancewideDestinationOauthParamsRequestBody) *NullableSetInstancewideDestinationOauthParamsRequestBody {
	return &NullableSetInstancewideDestinationOauthParamsRequestBody{value: val, isSet: true}
}

func (v NullableSetInstancewideDestinationOauthParamsRequestBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetInstancewideDestinationOauthParamsRequestBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


