/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints. * All `web_backend` APIs are not considered public APIs and are not guaranteeing backwards compatibility. 

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte

import (
	"encoding/json"
)

// OperationCreate struct for OperationCreate
type OperationCreate struct {
	WorkspaceId string `json:"workspaceId"`
	Name string `json:"name"`
	OperatorConfiguration OperatorConfiguration `json:"operatorConfiguration"`
}

// NewOperationCreate instantiates a new OperationCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperationCreate(workspaceId string, name string, operatorConfiguration OperatorConfiguration) *OperationCreate {
	this := OperationCreate{}
	this.WorkspaceId = workspaceId
	this.Name = name
	this.OperatorConfiguration = operatorConfiguration
	return &this
}

// NewOperationCreateWithDefaults instantiates a new OperationCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperationCreateWithDefaults() *OperationCreate {
	this := OperationCreate{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *OperationCreate) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *OperationCreate) GetWorkspaceIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *OperationCreate) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetName returns the Name field value
func (o *OperationCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OperationCreate) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OperationCreate) SetName(v string) {
	o.Name = v
}

// GetOperatorConfiguration returns the OperatorConfiguration field value
func (o *OperationCreate) GetOperatorConfiguration() OperatorConfiguration {
	if o == nil {
		var ret OperatorConfiguration
		return ret
	}

	return o.OperatorConfiguration
}

// GetOperatorConfigurationOk returns a tuple with the OperatorConfiguration field value
// and a boolean to check if the value has been set.
func (o *OperationCreate) GetOperatorConfigurationOk() (*OperatorConfiguration, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OperatorConfiguration, true
}

// SetOperatorConfiguration sets field value
func (o *OperationCreate) SetOperatorConfiguration(v OperatorConfiguration) {
	o.OperatorConfiguration = v
}

func (o OperationCreate) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["workspaceId"] = o.WorkspaceId
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["operatorConfiguration"] = o.OperatorConfiguration
	}
	return json.Marshal(toSerialize)
}

type NullableOperationCreate struct {
	value *OperationCreate
	isSet bool
}

func (v NullableOperationCreate) Get() *OperationCreate {
	return v.value
}

func (v *NullableOperationCreate) Set(val *OperationCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationCreate(val *OperationCreate) *NullableOperationCreate {
	return &NullableOperationCreate{value: val, isSet: true}
}

func (v NullableOperationCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


